languages = {'zh-Hans': '中文 (简体)', 'zh-Hant': '中文 (繁體)', 'en': 'English - 英语',
             'fr': 'Français - 法语', 'fr-CA': 'Français (Canada) - 法语（加拿大）', 'ru': 'Русский - 俄语',
             'es': 'Español - 西班牙语', 'de': 'Deutsch - 德语', 'ar': 'العربية - 阿拉伯语', 'ja': '日本語 - 日语',
             'ko': '한국어 - 韩语', 'pt-PT': 'Português (Portugal) - 葡萄牙语（葡萄牙）',
             'pt': 'Português (Brasil) - 葡萄牙语（巴西）', 'it': 'Italiano - 意大利语', 'uk': 'Українська - 乌克兰语',
             'id': 'Indonesia - 印尼语', 'hi': 'हिन्दी - 印地语', 'ms': 'Melayu - 马来语', 'vi': 'Tiếng Việt - 越南语',
             'my': 'မြန်မာ - 缅甸语', 'ne': 'नेपाली - 尼泊尔语', 'lzh': '中文 (文言)',
             'yue': '粵語 (繁體) - 粤语（繁体）', 'bo': 'བོད་སྐད་ - 藏语', 'ug': 'ئۇيغۇرچە - 维吾尔语',
             'fa': 'فارسی - 波斯语', 'pl': 'Polski - 波兰语', 'cs': 'Čeština - 捷克语', 'da': 'Dansk - 丹麦语',
             'tr': 'Türkçe - 土耳其语', 'nb': 'Norsk Bokmål - 挪威语', 'ur': 'اردو - 乌尔都语',
             'mn-Cyrl': 'Mongolian (Cyrillic) - 蒙古语（西里尔文）', 'mn-Mong': 'ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ - 蒙古语（传统蒙古文）',
             'cy': 'Cymraeg - 威尔士语', 'af': 'Afrikaans - 南非荷兰语', 'sq': 'Shqip - 阿尔巴尼亚语',
             'am': 'አማርኛ - 阿姆哈拉语', 'hy': 'Հայերեն - 亚美尼亚语', 'as': 'অসমীয়া - 阿萨姆语',
             'az': 'Azərbaycan - 阿塞拜疆语', 'bn': 'বাংলা - 孟加拉语', 'ba': 'Bashkir - 巴什基尔语',
             'eu': 'Euskara - 巴斯克语', 'bho': 'Bhojpuri - 博杰普尔语', 'brx': 'बड़ो - 博多语',
             'bs': 'Bosnian - 波斯尼亚语', 'bg': 'Български - 保加利亚语', 'ca': 'Català - 加泰罗尼亚语',
             'sn': 'chiShona - 绍纳语', 'hr': 'Hrvatski - 克罗地亚语', 'prs': 'دری - 达里语',
             'dv': 'ދިވެހިބަސް - 迪维希语', 'doi': 'Dogri - 多格拉语', 'nl': 'Nederlands - 荷兰语',
             'et': 'Eesti - 爱沙尼亚语', 'fo': 'Føroyskt - 法罗语', 'fj': 'Na Vosa Vakaviti - 斐济语',
             'fil': 'Filipino - 菲律宾语', 'fi': 'Suomi - 芬兰语', 'gl': 'Galego - 加利西亚语',
             'ka': 'ქართული - 格鲁吉亚语', 'el': 'Ελληνικά - 希腊语', 'gu': 'ગુજરાતી - 古吉拉特语',
             'ht': 'Haitian Creole - 海地克里奥尔语', 'ha': 'Hausa - 豪撒语', 'he': 'עברית - 希伯来语',
             'mww': 'Hmong Daw - 苗语', 'hu': 'Magyar - 匈牙利语', 'is': 'Íslenska - 冰岛语',
             'ig': 'Ásụ̀sụ́ Ìgbò - 伊博语', 'hne': 'Chhattisgarhi - 恰蒂斯加尔语', 'ikt': 'Inuinnaqtun - 伊努纳克屯语',
             'iu': 'ᐃᓄᒃᑎᑐᑦ - 因纽特语', 'iu-Latn': 'Inuktitut (Latin) - 因纽特语（拉丁文）', 'ga': 'Gaeilge - 爱尔兰语',
             'kn': 'ಕನ್ನಡ - 卡纳达语', 'ks': 'کٲشُر - 克什米尔语', 'kk': 'Қазақ Тілі - 哈萨克语',
             'km': 'ខ្មែរ - 高棉语', 'rw': 'Kinyarwanda - 基尼亚卢旺达语',
             'tlh-Latn': 'Klingon (Latin) - 克林贡语（拉丁文）', 'tlh-Piqd': 'Klingon (pIqaD) - 克林贡语 （pIqaD）',
             'gom': 'Konkani - 孔卡尼语', 'ku': 'Kurdî (Navîn) - 库尔德语（中部）',
             'kmr': 'Kurdî (Bakur) - 库尔德语（北方）', 'ky': 'Кыргызча - 吉尔吉斯语', 'lo': 'ລາວ - 老挝语',
             'lv': 'Latviešu - 拉脱维亚语', 'lt': 'Lietuvių - 立陶宛语', 'ln': 'Lingála - 林加拉语',
             'dsb': 'Dolnoserbšćina - 下索布语', 'lug': 'Ganda - 卢干达语', 'mk': 'Македонски - 马其顿语',
             'mai': 'Maithili - 迈蒂利语', 'mg': 'Malagasy - 马达加斯加语', 'ml': 'മലയാളം - 马拉雅拉姆语',
             'mt': 'Malti - 马耳他语', 'mi': 'Te Reo Māori - 毛利语', 'mr': 'मराठी - 马拉地语',
             'nya': 'Nyanja - 尼扬贾语', 'or': 'ଓଡ଼ିଆ - 奥里亚语', 'ps': 'پښتو - 普什图语', 'pa': 'ਪੰਜਾਬੀ - 旁遮普语',
             'otq': 'Hñähñu - 克雷塔罗奥托米语', 'ro': 'Română - 罗马尼亚语', 'run': 'Rundi - 隆迪语',
             'sm': 'Gagana Sāmoa - 萨摩亚语', 'sr-Cyrl': 'Српски (ћирилица) - 塞尔维亚语（西里尔文）',
             'sr-Latn': 'Srpski (latinica) - 塞尔维亚语（拉丁文）', 'st': 'Sesotho - 塞索托语',
             'nso': 'Sesotho sa Leboa - 北索托语', 'tn': 'Setswana - 塞茨瓦纳语', 'sd': 'سنڌي - 信德语',
             'si': 'සිංහල - 僧伽罗语', 'sk': 'Slovenčina - 斯洛伐克语', 'sl': 'Slovenščina - 斯洛文尼亚语',
             'so': 'Soomaali - 索马里语', 'sw': 'Kiswahili - 斯瓦希里语', 'sv': 'Svenska - 瑞典语',
             'ty': 'Reo Tahiti - 塔希提语', 'ta': 'தமிழ் - 泰米尔语', 'tt': 'Татар - 塔塔尔语',
             'te': 'తెలుగు - 泰卢固语', 'th': 'ไทย - 泰语', 'ti': 'ትግር - 提格里尼亚语', 'to': 'Lea Fakatonga - 汤加语',
             'tk': 'Türkmen Dili - 土库曼语(拉丁文)', 'hsb': 'Hornjoserbšćina - 上索布语',
             'uz': 'Uzbek (Latin) - 乌兹别克语（拉丁文）', 'xh': 'isiXhosa - 科萨语', 'yo': 'Èdè Yorùbá - 约鲁巴语',
             'yua': 'Yucatec Maya - 尤卡特克玛雅语', 'zu': 'Isi-Zulu - 祖鲁语'}


def get_languages():
    return languages
